{{- if .Values.provisioning.enabled }}
{{- $sa := include "deepfellow.provisioning.serviceAccountName" . }}
{{- if .Values.provisioning.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  labels:
    {{- include "deepfellow.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioning
{{- end }}
{{- end }}
