{{- range $name, $bRaw := .Values.modelBackends }}
{{- if include "deepfellow.backendEnabled" (dict "b" $bRaw) }}
{{- $b := include "deepfellow.normalizedBackend" (dict "context" $ "raw" $bRaw "name" $name) | fromYaml }}
{{- $component := printf "mb-%s" $name }}
{{- $secretName := include "deepfellow.credSecretName" (dict "context" $ "component" $component) }}
{{- $hfToken := $b.gguf.hfToken }}
{{- $sec := include "deepfellow.chartSecret" (dict "context" $ "secretName" $secretName "creds" (list $hfToken)) }}
---
{{- with $sec }}
{{ . }}
{{- end }}
{{- end }}
{{- end }}
