{{- if include "deepfellow.mongo.inChart" . }}
{{- $cred := include "deepfellow.credentials" . | fromYaml }}
{{- $secretName := include "deepfellow.credSecretName" (dict "context" . "component" "mongo") }}
{{- $sec := include "deepfellow.chartSecret" (dict "context" . "secretName" $secretName "creds" (list $cred.server.mongo.embedded.rootPassword $cred.server.mongo.password)) }}
{{- with $sec }}
{{ . }}
{{- end }}
{{- end }}
