{{- if include "deepfellow.milvus.inChart" . }}
{{- $cred := include "deepfellow.credentials" . | fromYaml }}
{{- $v := .Values.server.vectorDb }}
{{- $minioSecret := include "deepfellow.credSecretName" (dict "context" . "component" "minio") }}
{{- $minioSec := include "deepfellow.chartSecret" (dict "context" . "secretName" $minioSecret "creds" (list $cred.server.vectorDb.milvus.minio.rootUser $cred.server.vectorDb.milvus.minio.rootPassword)) }}
{{- with $minioSec }}
{{ . }}
{{- end }}
{{- end }}
